// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi55mTIYpxS2HWvSYiuYv-xOc_lmFuwJY',
    appId: '1:653162562389:web:f756c8b82aa704113765dc',
    messagingSenderId: '653162562389',
    projectId: 'chat-app-9ce0c',
    authDomain: 'chat-app-9ce0c.firebaseapp.com',
    storageBucket: 'chat-app-9ce0c.appspot.com',
    measurementId: 'G-7YWMBZHXJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdLnl-bnspibK1_7lkSABTv7e8Kiyd5k',
    appId: '1:653162562389:android:c53333eb305845ad3765dc',
    messagingSenderId: '653162562389',
    projectId: 'chat-app-9ce0c',
    storageBucket: 'chat-app-9ce0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrTd4H8xllknYDODJo1j-2EkhR8TlvOA4',
    appId: '1:653162562389:ios:58eb4c477596f1763765dc',
    messagingSenderId: '653162562389',
    projectId: 'chat-app-9ce0c',
    storageBucket: 'chat-app-9ce0c.appspot.com',
    iosClientId: '653162562389-7ctthls8387kfh2nd6hchdhh3e2dirjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrTd4H8xllknYDODJo1j-2EkhR8TlvOA4',
    appId: '1:653162562389:ios:58eb4c477596f1763765dc',
    messagingSenderId: '653162562389',
    projectId: 'chat-app-9ce0c',
    storageBucket: 'chat-app-9ce0c.appspot.com',
    iosClientId: '653162562389-7ctthls8387kfh2nd6hchdhh3e2dirjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
